---
# ==============================================================================
# Datacenter Role - Vars
# ==============================================================================

datacenter_state: "present"  # Options: present, absent
