---
# ==============================================================================
# CRI-O Role - Handlers
# ==============================================================================

- name: Restart crio
  service:
    name: crio
    state: restarted
    daemon_reload: yes
