---
# ==============================================================================
# Folders Role - Vars
# ==============================================================================

folder_state: "present"  # Options: present, absent
