---
# ==============================================================================
# VM Customization Role - Vars
# ==============================================================================

customization_state: "present"
ntp_server: "ntp.example.com"
dns_servers:
  - 8.8.8.8
  - 8.8.4.4
