zone "linuxplus.local" IN {
    type master;
    file "linuxplus.local.forward.zone";
    allow-update { none; };
};

zone "100.10.in-addr.arpa" IN {      
    type master;
    file "linuxplus.local.reverse.zone";
    allow-update { none; };
};
